//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountdownRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public int UserID { get; set; }
        public Nullable<System.Guid> UserKey { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
